### ISSUE TITLE
Functies

### ISSUE THREAD

**Issue by MarjoleinAardewijn** [CountNick/progressive-web-apps-1920#3]
Ik zie dat je allemaal functies hebt aangemaakt in app.js. Maar dit wil je eigenlijk voorkomen.
https://github.com/CountNick/progressive-web-apps-1920/blob/b4e0db0049396e500bfbcc16d9fe9bd11119f01a/server/app.js#L22

Je kan namelijk ook gebruik maken van de modules die je bijv bij WAFS hebt gemaakt door ze eerst te requiren bovenin `const api = require('path/to/module');` en ze dan gewoon aan te spreken als `api.getData()` bijvoorbeeld. En om bij de functies te komen moet je die dan wel nog exporteren `module.exports = { getData }`. Anders ziet hij de functies niet.

**Comment by CountNick** [comment]
Ik heb de data functies nu in een module die [api](https://github.com/CountNick/progressive-web-apps-1920/blob/master/server/modules/api.js) heet gestopt. Ik heb ook mijn [routes in een aparte module](https://github.com/CountNick/progressive-web-apps-1920/blob/master/server/routes/router.js) gezet waarin deze api module weer gebruikt word
