### ISSUE TITLE
Modules voor je functies in app.js

### ISSUE THREAD

**Issue by StefanGerrits2** [CountNick/progressive-web-apps-1920#5]
Ik stel voor om al je functies die je nu in je `app.js` heb staan om daar modules voor te maken.
Deze kan je exporten in een file met `module.exports`, en importen met `require('./path/to/file')`. Waarschijnlijk was je dit al van plan maar just to be sure :)

**Comment by CountNick** [comment]
Yess ga ik doen, maar zie dit meer als refactoring. Vind het tijdens development fijn om alles in 1 bestand te hebben:clown_face:

**Comment by CountNick** [comment]
Heb dit nu zo gedaan: [api](https://github.com/CountNick/progressive-web-apps-1920/blob/master/server/modules/api.js), [router](https://github.com/CountNick/progressive-web-apps-1920/blob/master/server/routes/router.js), [server](https://github.com/CountNick/progressive-web-apps-1920/blob/master/server/app.js). Is dit zo beter? of nog onduidelijker?
